spring.application.name=aipa
spring.datasource.url=jdbc:mysql://localhost:3306/aipa?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.config.import=optional:classpath:database_user.properties
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${AIPA_MAIL_USERNAME:}
spring.mail.password=${AIPA_MAIL_PASSWORD:}
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.jwt.secret=ZGljaG9uZ3RhaS1haXBhLXNlY3JldC1rZXktZm9yLWp3dC0yMDI2LTAyLTI1
app.jwt.expiration-ms=600000
